### ISSUE TITLE
run_command() should allow specify executable()

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#130]

**Comment by jpakkane** [comment]
Run_command means "run this command immediately and get the results". It is part of the configuration phase and is executed before a single line of code has been compiled. Thus it can not take an executable() because the binary does not exist when run_command() tries to run.

What are you trying to actually accomplish with this?

**Comment by ignatenkobrain** [comment]
I tried to create program (C language) to get version from other file (header) and use it in meson. But I scripted it on python. If you don't think that we need to fix this - close bug, no problems ;)
