### ISSUE TITLE
Boost: unit_test_framework dependency

### ISSUE THREAD

**Issue by sils1297** [jpakkane/meson#29]
I've created a meson.build file with

```boost_dep = dependency('boost', modules : ['thread', 'system', 'unit_test_framework'])```

When executing, I get the following message:

```Meson encountered an error in file meson.build, line 3, column 0:
Requested Boost module "unit_test_framework" not found.```

However if I execute my cmake file with

```find_package(Boost COMPONENTS unit_test_framework thread system REQUIRED)```

the build does work.

This is obviously unexpected behaviour and hinders me from using meson for an own project. Or am I doing something wrong?

**Comment by jpakkane** [comment]
The problem with Boost and unit_tests in particular is that they don't provide pkg-config files and their file layout is a bit of a wild west, so properly autodetecting it is hard. I have updated the code so now it works for some cases at least. Please try it out and let me know if it's working for you. Note however the following:

* the module is called 'test' and not 'unit_testing_framework'
* it autolinks Boost's main method (so you can't have one in your .cpp files)

If the latter is a problem to you, please write a simple example of how you have set up your project below. Thanks.

**Comment by axxel** [comment]
The checked in boost framework test (the unit test part) does not work for me: (... well, it did in the end.)

1. The configure step 'worked', i.e. did not complain, even though I had not installed ubuntu's libboost-test-dev package. It turns out, the boost/test include directory is part of the libboost-dev package. The libboost-test-dev package only adds a bunch of .a/.so files. This may arguably be a bug in the debian boost packges. Fixing it in meson would require to check for both source and lib parts for those modules that have lib parts.

2. After installing the missing package, the compile still failed with an unresolved symbol error. The link command did not specify any of the boost unit test libs:
```[1/1] c++   -o utf utf.dir/unit_test.cpp.o```
It turned out, I got hung up on not knowing how to properly re-configure in this case. I thought having meson rerun (by touching the meson.build) and running ninja again should do the trick. I had to ```rm -rf *``` in my test-build dir and start over to fix this. Is this the way to go? Is this a followup problem of the first (not detecting the missing libs in the first place)?

**Comment by jpakkane** [comment]
Currently Meson caches the results of dependency checks if they are successful. In Boost's case which library components are available on your system. The problem comes from the fact that you can't know which Boost modules have library parts. Some do, some don't. Some can be built either way. Because of this reason, among other things, it would be super awesome if Boost libraries provided pkg-config files because otherwise a build system has to revert to guesswork.

Rescanning dependencies every time Meson is run would be a solution but it would slow down the common case where system dependencies have not changed.

**Comment by jpakkane** [comment]
Since unit testing framework now works, closing this. If there are other issues, please open new tickets. Thanks.
