### ISSUE TITLE
Qt4 support

### ISSUE THREAD

**Issue by philroberts** [jpakkane/meson#35]
I am attempting to migrate an existing project from CMake to Meson.  The project uses Qt4.  I tried a quick copy-paste of the Qt5 dependency code but discovered a wrinkle: I am on OSX, and installed Qt4 from the .dmg installer.  This means pkg-config doesn't know about it.  A brief inspection of the relevant CMake stuff suggests they query qmake for config information.  Is this something you would consider adding to Meson?

**Comment by jpakkane** [comment]
This is a bit of a long explanation, so please bare with me.

The original design for Qt support was to have native, world class Qt5 support out of the box and to make the system introspection/code generation good enough that it can be used to write your own Qt4 support. The reasoning was that most users of Meson would probably start with a new project in Qt5 or switch to using Meson when they make their 4->5 transition. Also, if you can express Qt4 build rules in Meson's own language then you can pretty much describe anything. :)

The Qt5 support also needs hardening, as it currently uses pkg-config which makes it not portable to Windows/OSX. I haven't touched that because I don't have any experience using Qt on those platforms.

All that said the optimal case for this going forward would be the following:

- verifying that run_process, generator & co are sufficiently good that they alone can be used to implement Qt4 support
- once that is working, look at the resulting Meson build definition, and if it is too complex, add suitable helper functionality to core
- expand Qt5 support to do the qmake thing on OSX and Windows

This is obviously only a rough outline and much depends on how much people really want Qt4 support and all that.

Any ideas or comments?

**Comment by philroberts** [comment]
OK, I'll see how far I can get with Meson primitives.  I don't super care about this, and I can see where Qt4 support would be low priority. :)  It should be possible to get Qt info into pkg-config, probably by installing Qt through macports as well, so I might try that approach also.

We do also build on windows and linux, so I will investigate the situation there too if I get it running on OSX.

**Comment by jpakkane** [comment]
Trunk was just refactored to move the moc bits into a standalone module. This should make adding Qt4 support a lot easier (basically just copypaste the qt5 module and dependency and tweak the commands accordingly).

**Comment by jpakkane** [comment]
Trunk now has Qt4 support. It doesn't do the qmake flag thing but it can be added if there's demand for it.
