### ISSUE TITLE
support for abs paths for configure

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#67]
for example, by GNU Coding Standards (https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) `localstatedir` should be `${prefix}/var`, but when we're packaging for Fedora it's not so.

```
[brain@x1carbon meson]$ rpm --eval %{_localstatedir}
/var
[brain@x1carbon meson]$ rpm --eval %{_prefix}
/usr
```

and I should specify `--localstatedir=%{_localstatedir}` will set abs path which not allowed by meson.

This is just specific case where i need have abs path, but I think we should allow people to use abs paths.

**Comment by jpakkane** [comment]
If you specify a custom install directory as an absolute path, then the install happens there (or specifically to ${DESTDIR}/yourdir). It behaves like this because it is uncommon to install stuff outside /usr, so that has been made the default. If there is a use case where installing stuff outside prefix is common, then we can consider it.

**Comment by ignatenkobrain** [comment]
@jpakkane it's common for most distros (for localstatedir). AFAIK, Ubuntu, Debian, Fedora, Archlinux uses /var as localstatedir instead of $prefix/var

**Comment by ignatenkobrain** [comment]
let's close this now. if anyone will have problems - we will fix.
