### ISSUE TITLE
Tried to set global arguments after they have become immutable.

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#93]
```
Meson encountered an error in file client/meson.build, line 1, column 0:
Tried to set global arguments after they have become immutable.
```

`meson.build`:
```
...
add_global_arguments('-DAS_COMPILATION', language : 'c')
add_global_arguments('-DLOCALEDIR="@0@"'.format(get_option('localedir')), language : 'c')

subdir('libappstream-glib')
#if get_option('enable-builder')
#  subdir('libappstream-builder')
#endif
subdir('client')
```

`client/meson.build`:
```
add_global_arguments('-DG_LOG_DOMAIN="As"', language : 'c')
...
```

**Comment by jpakkane** [comment]
You most likely create a target in subdir libappstream-glib. After that you can't add global arguments any more (to avoid ambiguity). If you wish to add -DG_LOG_COMAIN="as" to every single compile (even those in libappstream-glib), then set it at the top level before calling subdir.

If you only want to have the flag on targets in the client subdir, then you need to specify it in their target definitions like this:

    executable('foo', 'foo.c',
      ...
      c_args : '-DG_LOG_DOMAIN="As"')

**Comment by ignatenkobrain** [comment]
@jpakkane how about feature like `add_local_args()` ? it will add args to all targets in current meson.build file.

**Comment by jpakkane** [comment]
That is not by design. The most annoying feature of CMake and Autotools is that they have a gazillion different ways to add compiler flags. In Meson there are only two: global flags that are the same for every single compile and target specific flags which are explicit. The reason for this is that you can tell what flags are used for a target by looking only in one place.

If you wish to share flags between multiple targets in a same directory put them in a variable.

**Comment by ignatenkobrain** [comment]
ah, ok. makes sense
